# Generated by Django 2.1.5 on 2019-03-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='file_name',
            field=models.CharField(default='no_file_name', max_length=200),
            preserve_default=False,
        ),
    ]
