# Generated by Django 2.1.5 on 2019-03-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0002_clip_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='anomaly',
            field=models.FloatField(default=0),
        ),
    ]
